services:
  - type: web
    name: reports-app
    env: ruby
    buildCommand: bundle install && bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reports-db
          property: connectionString
  databases:
    - name: reports-db
      engine: postgresql
      version: 13
      initialDiskSizeGB: 10
